---
# tasks file for prepare_web
- name: Install JRE
  apt:
    name: default-jre
    state: present
    update_cache: yes

- name: Install tomcat9
  apt:
    name: tomcat9
    state: present
  notify:
    - start tomcat9
