---
# tasks file for web
- name: Copy java app from build server to web server by rsync
  synchronize: src=/home/GIT/boxfuse/target/hello-1.0.war dest=/var/lib/tomcat9/webapps
  delegate_to: 130.193.55.61
  notify:
    - restart tomcat9
